@CoreBanking.Api_HostAddress = https://localhost:7065

@nid=0012345678
GET {{CoreBanking.Api_HostAddress}}/api/authentications/{{nid}}

###

POST {{CoreBanking.Api_HostAddress}}/api/authentications
Content-Type: application/json

{
  
  "civilRegistry": {
    "nationalCode": "0012345678",
    "firstName": "Ali",
    "lastName": "Ahmadi",
    "birthDate": "1990-01-01T00:00:00",
    "isAlive": true
  },
  "centralBankCreditCheck": {
    "isValid": true,
    "reason": "Validation Success",
    "checkedAt": "2025-12-13T18:06:57.3575445+03:30"
  },
  "policeClearance": {
    "hasCriminalRecord": false,
    "description": "No Criminal Record",
    "checkedAt": "2025-12-13T18:06:57.3122191+03:30"
  },
  "authentication": null

}

###

POST {{CoreBanking.Api_HostAddress}}/api/customers
Content-Type: application/json

{
  "nationalCode": "0012345678",
  "firstName": "Ali",
  "lastName": "Ahmadi",
  "createdAt": "0001-01-01T00:00:00"
}

###

GET {{CoreBanking.Api_HostAddress}}/api/customers

###
@id=ecc3cdae-c891-4408-44a2-08de3a67f5b2
DELETE {{CoreBanking.Api_HostAddress}}/api/customers/{{id}}

###
@id=ecc3cdae-c891-4408-44a2-08de3a67f5b2
GET {{CoreBanking.Api_HostAddress}}/api/customers/{{id}}

###
@id=1fd61061-ce4e-4ba1-44a3-08de3a67f5b2
PUT {{CoreBanking.Api_HostAddress}}/api/customers/{{id}}
Content-Type: application/json

{
  "id":"1fd61061-ce4e-4ba1-44a3-08de3a67f5b2",
  "nationalCode": "0012345678",
  "firstName": "Ehsan",
  "lastName": "Ahmadi",
  "createdAt": "0001-01-01T00:00:00",
  "accounts": []
}

###
