@CoreBanking.Api_HostAddress = https://localhost:7065


POST {{CoreBanking.Api_HostAddress}}/api/customers
Content-Type: application/json

{
  "nationalCode": "0098765432",
  "firstName": "Reza",
  "lastName": "Mohammadi",
  "createdAt": "0001-01-01T00:00:00"
}

###

POST {{CoreBanking.Api_HostAddress}}/api/authentications/login
Content-Type: application/json

{
 
  "email": "ali@gmail.com",
  "password": "Ehsanadsad2412@",
  "rememberMe":false
}

###


@id=0098765432
GET {{CoreBanking.Api_HostAddress}}/api/authentications/{{id}}

###

POST {{CoreBanking.Api_HostAddress}}/api/authentications
Content-Type: application/json

{
  "civilRegistry": {
    "nationalCode": "0098765432",
    "firstName": "Reza",
    "lastName": "Mohammadi",
    "birthDate": "1985-06-15T00:00:00",
    "isAlive": true
  },
  "centralBankCreditCheck": {
    "isValid": true,
    "reason": "Validation Success",
    "checkedAt": "2025-12-15T16:41:12.0058635+03:30"
  },
  "policeClearance": {
    "hasCriminalRecord": false,
    "description": "No Criminal Record",
    "checkedAt": "2025-12-15T16:41:11.9914978+03:30"
  },
  "registeredAuthentication": null
  }

###

GET {{CoreBanking.Api_HostAddress}}/api/customers

###

POST {{CoreBanking.Api_HostAddress}}/api/accounts
Content-Type: application/json

{
  "customerId": "b9a86905-188f-4e5f-dd7d-08de3bdab975"
}

###

POST {{CoreBanking.Api_HostAddress}}/api/authentications/register
Content-Type: application/json

{
  "email": "reza@gmail.com",
  "customerId": "b9a86905-188f-4e5f-dd7d-08de3bdab975",
  "password": "Ehsanadsad2412@",
  "confirmPassword": "Ehsanadsad2412@"
}

###

POST {{CoreBanking.Api_HostAddress}}/api/authentications/logout

###
